# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - TicketHelp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4


      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'


      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
      
      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
        
  # Optional: Run tests (uncomment when tests are stable)
  # - name: Run tests
  #   run: |
  #     source venv/bin/activate
  #     pytest -q


      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x 'venv/*'

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_845FE5A135E14EBE9C00EE7D30AFABF6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F6578DB7F16E4570802B504D92E5A94F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_69ECD3A85E114756A546286986E047B5 }}


      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TicketHelp'
          slot-name: 'Production'
          package: '.'
          